# Generated by Django 3.0.3 on 2020-07-23 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CatCamaras',
            fields=[
                ('id_CatCamara', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.BooleanField(null=True)),
                ('nombre', models.CharField(max_length=255, null=True)),
                ('ip', models.CharField(max_length=255, null=True)),
                ('latitud', models.DecimalField(decimal_places=5, max_digits=5, null=True)),
                ('longitud', models.DecimalField(decimal_places=5, max_digits=5, null=True)),
                ('creado', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CatOrganizaciones',
            fields=[
                ('id_CatOrganizacion', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.BooleanField(null=True)),
                ('nombre', models.CharField(max_length=255, null=True)),
                ('creado', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CatTipos',
            fields=[
                ('id_CatTipo', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.BooleanField(null=True)),
                ('nombre', models.CharField(max_length=255, null=True)),
                ('creado', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Registros',
            fields=[
                ('id_Registro', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.BooleanField(null=True)),
                ('valor', models.DecimalField(decimal_places=5, max_digits=5, null=True)),
                ('creado', models.DateTimeField(auto_now=True, null=True)),
                ('nombre', models.CharField(max_length=255, null=True)),
                ('id_CatCamara', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DistSocialApp.CatCamaras')),
                ('id_CatTipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DistSocialApp.CatTipos')),
            ],
        ),
        migrations.CreateModel(
            name='CatUsuarios',
            fields=[
                ('id_CatUsuario', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.BooleanField(null=True)),
                ('usuario', models.CharField(max_length=255, null=True)),
                ('pw', models.CharField(max_length=255, null=True)),
                ('nombre', models.CharField(max_length=255, null=True)),
                ('creado', models.DateTimeField(auto_now=True, null=True)),
                ('id_CatOrganizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DistSocialApp.CatOrganizaciones')),
            ],
        ),
        migrations.CreateModel(
            name='CatLocalidades',
            fields=[
                ('id_CatLocalidad', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.BooleanField(null=True)),
                ('nombre', models.CharField(max_length=255, null=True)),
                ('latitud', models.DecimalField(decimal_places=5, max_digits=5, null=True)),
                ('longitud', models.DecimalField(decimal_places=5, max_digits=5, null=True)),
                ('creado', models.DateTimeField(auto_now=True, null=True)),
                ('id_CatOrganizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DistSocialApp.CatOrganizaciones')),
            ],
        ),
        migrations.AddField(
            model_name='catcamaras',
            name='id_CatLocalidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DistSocialApp.CatLocalidades'),
        ),
    ]
