# Generated by Django 3.0.3 on 2020-07-23 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DistSocialApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catcamaras',
            name='creado',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='catlocalidades',
            name='creado',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='catorganizaciones',
            name='creado',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='cattipos',
            name='creado',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='catusuarios',
            name='creado',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='registros',
            name='creado',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
