# Generated by Django 3.0.3 on 2020-08-17 20:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('DistSocialApp', '0005_auto_20200817_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registros',
            name='creado',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
