# Generated by Django 3.0.3 on 2020-09-10 20:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('DistSocialApp', '0006_auto_20200817_1547'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatDispositivos',
            fields=[
                ('id_CatDispositivo', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.BooleanField(null=True)),
                ('mac', models.CharField(max_length=255, null=True)),
                ('creado', models.DateTimeField(default=django.utils.timezone.now, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Configuraciones',
            fields=[
                ('id_Configuracion', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.BooleanField(null=True)),
                ('nombre', models.CharField(max_length=100, null=True)),
                ('valor', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
