# Generated by Django 3.0.3 on 2020-09-10 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DistSocialApp', '0007_catdispositivos_configuraciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuraciones',
            name='tipo',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
