# Generated by Django 3.0.3 on 2020-09-14 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DistSocialApp', '0008_configuraciones_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servers',
            fields=[
                ('id_Server', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.BooleanField(null=True)),
                ('nombre', models.CharField(max_length=100, null=True)),
                ('puerto', models.IntegerField(null=True)),
                ('user', models.CharField(max_length=100, null=True)),
                ('pwd', models.CharField(max_length=100, null=True)),
                ('nombre_db', models.CharField(max_length=100, null=True)),
                ('tipo', models.CharField(max_length=10, null=True)),
            ],
        ),
    ]
